// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7nRP_WouWD6JfAWwYH8KMHK04Ul5_OSo',
    appId: '1:446534662592:web:f85d7cd59e7fa7c763b025',
    messagingSenderId: '446534662592',
    projectId: 'neopolis-86bc6',
    authDomain: 'neopolis-86bc6.firebaseapp.com',
    storageBucket: 'neopolis-86bc6.appspot.com',
    measurementId: 'G-ZJZEZVXLE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqD2eaTTqiLeOxy1EvVZ_yCeZ9eI6nQQ',
    appId: '1:446534662592:android:cf5d4b04283a022663b025',
    messagingSenderId: '446534662592',
    projectId: 'neopolis-86bc6',
    storageBucket: 'neopolis-86bc6.appspot.com',
  );
}
